# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2022-06-15T16:10:43+00:00

from __future__ import annotations

from fastapi import FastAPI

from .core import (
    get_start_video_core,
    get_stop_video_core,
    get_take_picture_core,
)
from .models import Media

app = FastAPI(title="FastAPI camera control", version="0.0.1", openapi_url="/openapi.json")


@app.get('/start_video', response_model=Media)
def get_start_video() -> Media:
    response = get_start_video_core()
    return response


@app.get('/stop_video', response_model=Media)
def get_stop_video() -> Media:
    response = get_stop_video_core()
    return response


@app.get('/take_picture', response_model=Media)
def get_take_picture() -> Media:
    response = get_take_picture_core()
    return response
